### ISSUE TITLE
Adaptation for new X.509 authentication model needed in hotspot-config

### ISSUE THREAD

**Issue by sa0bux** [Guru-RF/SVXSpot#17]
AUTH_KEY is deprecated, hotspot-config could ask for CERT_EMAIL 

 The reflector connection will be authenticated using X.509 certificates. Both the server and the client  requires  authentica‐
       tion. The AUTH_KEY authentication method that were previously used is deprecated. The certificate generation process is mostly
       automated. The contents of the certificate can be customized using the configuration variables with name prefix CERT_. Default
       values  are good in most cases. CERT_EMAIL may be good to specify so that the SvxLink node owner can be contacted. Ask the re‐
       flector sysop what the convention is.

**Comment by ure** [comment]
The issue raised about the AUTH_KEY deprecation and the use of CERT_EMAIL for hotspot-config seems to be based on features present in the master (development) branch of the SvxLink repository. These features are not yet available in the release channel.

The most recent official release of SvxLink was on February 25, 2024 ([release details](https://github.com/sm0svx/svxlink/releases)). Our repository is based on the main release channel and does not include these development features.

We will integrate these new features into our repository once they are officially released by SvxLink. In the meantime, for users who need these cutting-edge features, they can switch to the development branch by using update-svxlink-main.sh. However, please note that this will require manual configuration changes, and we recommend proceeding with caution.

**Comment by ure** [comment]
We maintain an additional branch that follows the main SVXLink tree:
[SVXSpotMain on GitHub](https://github.com/Guru-RF/SVXSpotMain)

This branch includes a test image featuring DNS_SRV support and key requests via CALLSIGN. Once the reflector sysop signs the certificate, you’re all set to go!
