### ISSUE TITLE
that is what happend with raspbian bookworm 32bit lastest update

### ISSUE THREAD

**Issue by sa7aux** [Guru-RF/SVXSpot#9]
Hi howto solve this? maybe more people have same problem when thet install it.

a fix sone as possible, thanks.

//bjorne sa7aux

× svxlink_gpio_setup.service - SvxLink repeater control software GPIO setup
     Loaded: loaded (/lib/systemd/system/svxlink_gpio_setup.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-04-23 13:20:43 CEST; 2s ago
       Docs: man:svxlink(1)
    Process: 1194 ExecStart=/usr/sbin/svxlink_gpio_up (code=exited, status=1/FAILURE)
   Main PID: 1194 (code=exited, status=1/FAILURE)
        CPU: 40ms

Apr 23 13:20:43 svxspot svxlink_gpio_up[1198]: chown: cannot access '/sys/class/gpio/gpio12/value': No such file or directory
Apr 23 13:20:43 svxspot svxlink_gpio_up[1199]: chgrp: cannot access '/sys/class/gpio/gpio12/value': No such file or directory
Apr 23 13:20:43 svxspot svxlink_gpio_up[1200]: chmod: cannot access '/sys/class/gpio/gpio12/value': No such file or directory
Apr 23 13:20:43 svxspot svxlink_gpio_up[1194]: /usr/sbin/svxlink_gpio_up: 60: echo: echo: I/O error
Apr 23 13:20:43 svxspot svxlink_gpio_up[1204]: chown: cannot access '/sys/class/gpio/gpio16/value': No such file or directory
Apr 23 13:20:43 svxspot svxlink_gpio_up[1205]: chgrp: cannot access '/sys/class/gpio/gpio16/value': No such file or directory
Apr 23 13:20:43 svxspot svxlink_gpio_up[1206]: chmod: cannot access '/sys/class/gpio/gpio16/value': No such file or directory
Apr 23 13:20:43 svxspot systemd[1]: svxlink_gpio_setup.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 13:20:43 svxspot systemd[1]: svxlink_gpio_setup.service: Failed with result 'exit-code'.
Apr 23 13:20:43 svxspot systemd[1]: Failed to start svxlink_gpio_setup.service - SvxLink repeater control software GPIO setup.

**Comment by ure** [comment]
We prevent kernel upgrades with our hotspot-config tool to prevent this.
You can if you wish use GPIOD instead of sysfs gpio ... or adjust to the new gpio layout in the new kernel.
Last i checked the audio module does not compile on this kernel branch ... we are waiting for a general update, if that's fixed upstream we will provide a new image

**Comment by sa7aux** [comment]
Okidoki, i will find away to solve it :)

//bjorne sa7aux

**Comment by BY-HomeAssi** [comment]
Hello, if you change the following parameters in /etc/svxlink/gpio.conf, everything works again.

old entries:
GPIO_IN_LOW="12"
GPIO_OUT_LOW="16"

new entries:
GPIO_IN_LOW="gpio12"
GPIO_OUT_LOW="gpio16"

**Comment by ure** [comment]
Is there a new kernel already, last time i checked it were nrs < 500 for the internal gpio with the gpio stack. Als the audio driver would not compile due to changed symbols.

I'll chek on a later time to see if things stabilized with the latest rapsi kernel.

**Comment by ure** [comment]
fixed in latest image
